---
name: 'openerserver'
abstract: 'Http Container for run any code with http server'
version: '1.1'
author:
  - 'Larry Wang <a@openerserver.com>'
distribution_type: 'app'
license: 'Apache'
requires:
  AnyEvent: '0'
  EV: '0'
  LWP::MediaTypes: '0'
  JSON::XS: '0'
  HTTP::Parser2::XS: '0'
  IO::All: '0'
  URI::Escape::XS: '0'
  AnyEvent::HTTP: '0'
  AnyEvent::Fork: '0'
  Digest::MD5: '0'

dynamic_config: 0
resources:
  license: http://www.apache.org/licenses/
  homepage: https://www.openerserver.com
  repository: https://github.com/openerserver/openerserver_perl/
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
generated_by: 'Module::Install version 0.77'
